---
title: "Xinhua, Diplomacy, and Chinese Foreign Aid"
author: ["Lucie Lu","Miles D. Williams"]
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    number_sections: yes
classoption: fleqn
fontfamily: mathpazo
fontsize: 12pt
bibliography: ref.bib
link-citations: yes
linkcolor: blue
header-includes:
  - \usepackage{amsmath}
  - \usepackage{setspace}
  - \setlength{\mathindent}{15pt}
  - \setlength\parindent{24pt}
  - \setlength{\parskip}{0.0pt plus 1.0pt}
  - \doublespacing
  - \newtheorem{theorem}{Theorem}[section]
  - \newtheorem{lemma}[theorem]{Lemma}
  - \newtheorem{proposition}[theorem]{Proposition}
  - \newtheorem{corollary}[theorem]{Corollary}
  - \newenvironment{proof}[1][Proof]{\begin{trivlist}
      \item[\hskip \labelsep {\bfseries Proof}]}{\end{trivlist}}
  - \newenvironment{definition}[1][Definition]{\begin{trivlist}
      \item[\hskip \labelsep {\bfseries 1}]}{\end{trivlist}}
  - \newenvironment{example}[1][Example]{\begin{trivlist}
      \item[\hskip \labelsep {\bfseries 1}]}{\end{trivlist}}
  - \newenvironment{remark}[1][Remark]{\begin{trivlist}
      \item[\hskip \labelsep {\bfseries 1}]}{\end{trivlist}}
  - \newcommand{\qed}{\nobreak \ifvmode \relax \else
      \ifdim\lastskip<1.5em \hskip-\lastskip
      \hskip1.5em plus0em minus0.5em \fi \nobreak
      \vrule height0.75em width0.5em depth0.25em\fi}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \floatplacement{figure}{!t}
abstract: "Absent formal avenues of transparency, how do China's efforts at gaining international recognition and promoting good relations with aid recipients play out in Beijings foreign aid giving? We bring a novel perspective to this issue by considering Chinese media coverage of developing countries intended for foreign audiences and China’s bilateral diplomatic activities. These measures capture two distinct but related aspects of China’s foreign policy: status/legitimacy in the eyes of a foreign (predominantly Western) audience and south-south diplomacy. To the extent that China’s development finance complements these goals, we expect greater coverage of a developing country in a Chinese media outlet directed to foreign readers and greater bilateral diplomatic activity to correlate with greater Chinese foreign aid giving. To test this expectation we merge AidData’s Chinese development finance dataset with two newly available datasets: (1) AidData’s compiled yearly counts of bilateral official diplomatic visits from China and (2) millions of English edition Xinhua news articles from 2000 to 2014 scraped by the Cline Center for Advanced Social Research. We find that greater media coverage of developing countries targeted at a foreign audience via the English version of Xinhua and the number of diplomatic visits to a developing country predict greater receipt of Chinese aid. Our results support the view that Chinese aid allocation patterns map to China’s broader diplomacy and legitimacy seeking objectives on the world stage."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```


# Introduction 

China neither reports its foreign aid spending to international organizations, as do Development Assistance Committee (DAC) members to the OECD, nor does China publish its aid expenditures in a public database, as does the United States in USAID's *Greenbook*. @fuchsRudyak2019 cite this fact as a reason Western governments assume Beijing deliberately keeps its international development finance a secret. 

However, many observe an unmistakable connection between China's version of Official Development Assistance (ODA) and its political and material goals. These ambitions include international recognition and closer diplomatic ties with recipients in what China calls "south-south cooperation." While distinct, these objectives have one thing in common: they are difficult to accomplish *in secret.* They require visibility. So, absent traditional modes of transparency, *how does China's foreign aid relate to Beijing's efforts at public diplomacy and international recognition?*

We tackle this question by considering Chinese media coverage of developing countries intended for foreign audiences and China’s bilateral diplomatic activities. These measures capture two distinct but related aspects of China’s foreign policy: status/legitimacy in the eyes of a foreign (predominantly Western) audience and south-south diplomacy. To the extent that China’s development finance complements these goals, we expect greater coverage of a developing country in a Chinese media outlet directed to foreign readers and greater bilateral diplomatic activity to correlate with greater Chinese foreign aid giving. To test this expectation we merge AidData’s Chinese development finance dataset with two newly available datasets: (1) AidData’s compiled yearly counts of bilateral official diplomatic visits from China and (2) millions of English edition Xinhua news articles from 2000 to 2014 scraped by the Cline Center for Advanced Social Research. We find that greater media coverage of developing countries targeted at a foreign audience via the English version of Xinhua and the number of diplomatic visits to a developing country predict greater receipt of Chinese aid. Our results support the view that Chinese aid allocation patterns map to China’s broader diplomacy and legitimacy seeking objectives on the world stage. 

This work further helps in dispelling the notion that China purposely engages in development finance in secret. Much to the contrary, China complements its aid giving with visible diplomatic envoys and greater external-facing media coverage.


# Motivations behind Chinese Foreign Aid

China's motivations for giving foreign aid to developing countries mirror, in many ways, the motivations of Western donors. While recipient needs, in part, predicate Chinese assistance, so do Beijing's political and economic interests. For instance, evidence suggests that China targets more finance toward poorer countries and does not systematically favor authoritarian over democratic recipients [@dreherEtAl2018]. At the same time, China seems to give more aid to countries that import more goods from China, while it gives less aid to those that officially recognize Taiwan [@dreherFuchs2015]. Further, China's Official Financing disproportionately goes to countries with more natural resources, greater UN General Assembly voting alignment, and with more capacity to repay loans [@dreherEtAl2021].

Surveys of policymakers in 126 countries demonstrate the diplomatic impact that these investments have had.^[Reported in blog post ["China's Financial Statecraft: Winning Africa one Yuan at a Time?"](https://www.aiddata.org/blog/chinas-financial-statecraft-winning-africa-one-yuan-at-a-time) by AidData on March 22, 2018. Accessed March 3, 2022]. Compared to a first survey wave in 2014, responses in 2017 showed an increase in evaluations of China's influence with policymakers in developing countries. It would be naive to suppose this is a side-effect, rather than a goal, of China's development finance and other investments.

If its diplomatic motives for giving aid parallel those of other donor governments, visibility is surely a major concern for Beijing. Visual branding of aid has emerged as a growing concern among donors. The United States Agency for International Development (USAID), for example, cites its "new 'brand identity'" as instrumental in promoting the visibility of 2004-2005 tsunami relief.^[See USAID's resource page on branding: [usaid.gov/branding](https://www.usaid.gov/branding).] A US State Department report from 2004 further claims that better branding contributed to a doubling of favorable attitudes toward the US in Indonesia. Pew Research supports this view, finding that nearly 80$\%$ of Indonesians surveyed "said that post-tsunami aid from the US had improved their impression of America."^[["Does humanitarian aid improve America's image?"](https://www.pewresearch.org/global/2012/03/06/does-humanitarian-aid-improve-americas-image/) Published by Pew Research March 6, 2012. Accessed March 3, 2022.] 


# References
