---
title: "Friends Get More Money, Attention and Handshakes: Chinese Foreign Aid, Xinhua and Diplomatic Visits"
author: ["Lucie Lu","Miles D. Williams"]
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    number_sections: yes
classoption: fleqn
fontfamily: mathpazo
fontsize: 12pt
bibliography: ref_xinhua.bib
link-citations: yes
linkcolor: blue
header-includes:
  - \usepackage{amsmath}
  - \usepackage{setspace}
  - \setlength{\mathindent}{15pt}
  - \setlength\parindent{24pt}
  - \setlength{\parskip}{0.0pt plus 1.0pt}
  - \doublespacing
  - \newtheorem{theorem}{Theorem}[section]
  - \newtheorem{lemma}[theorem]{Lemma}
  - \newtheorem{proposition}[theorem]{Proposition}
  - \newtheorem{corollary}[theorem]{Corollary}
  - \newenvironment{proof}[1][Proof]{\begin{trivlist}
      \item[\hskip \labelsep {\bfseries Proof}]}{\end{trivlist}}
  - \newenvironment{definition}[1][Definition]{\begin{trivlist}
      \item[\hskip \labelsep {\bfseries 1}]}{\end{trivlist}}
  - \newenvironment{example}[1][Example]{\begin{trivlist}
      \item[\hskip \labelsep {\bfseries 1}]}{\end{trivlist}}
  - \newenvironment{remark}[1][Remark]{\begin{trivlist}
      \item[\hskip \labelsep {\bfseries 1}]}{\end{trivlist}}
  - \newcommand{\qed}{\nobreak \ifvmode \relax \else
      \ifdim\lastskip<1.5em \hskip-\lastskip
      \hskip1.5em plus0em minus0.5em \fi \nobreak
      \vrule height0.75em width0.5em depth0.25em\fi}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \floatplacement{figure}{!t}
  - \usepackage{caption}\captionsetup[table]{skip=5pt}
  - \usepackage{dcolumn}
  - \usepackage{rotating}
  - \usepackage{caption}\DeclareCaptionLabelFormat{AppendixTables}{A.#2}

Abstract: "Absent formal avenues of transparency, how do China's efforts at gaining international recognition and promoting good relations with aid recipients play out in Beijings foreign aid giving? We bring a novel perspective to this issue by considering Chinese media coverage of developing countries intended for foreign audiences and China’s bilateral diplomatic activities. These measures capture two distinct but related aspects of China’s foreign policy: status/legitimacy in the eyes of a foreign (predominantly Western) audience and south-south diplomacy. To the extent that China’s development finance complements these goals, we expect greater coverage of a developing country in a Chinese media outlet directed to foreign readers and greater bilateral diplomatic activity to correlate with greater Chinese foreign aid giving. To test this expectation we merge AidData’s Chinese development finance dataset with two newly available datasets: (1) AidData’s compiled yearly counts of bilateral official diplomatic visits from China and (2) millions of English edition *Xinhua* news articles from 2000 to 2014 scraped by the Cline Center for Advanced Social Research. We find that greater media coverage of developing countries targeted at a foreign audience via the English version of *Xinhua* and the number of diplomatic visits to a developing country predict greater receipt of Chinese aid. Our results support the view that Chinese aid allocation patterns map to China’s broader diplomacy and legitimacy seeking objectives on the world stage."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```


# Introduction 

China's overseas development financing now surpasses that of the United States, the World Bank, and several other multilateral development and lending institutions combined. But despite the mammoth proportions of Beijing's aid (and increasingly debt) that it issues worldwide, the motives behind its overseas activities remain a mystery. China neither reports its foreign aid spending to international organizations, as do Development Assistance Committee (DAC) members to the OECD, nor does China publish its aid expenditures in a public database, as does the United States in USAID's *Greenbook*. For this reason, many Western governments assume Beijing deliberately keeps its international development finance a secret [@fuchsRudyak2019]. 

Although Beijing has primarily focused on its immediate surrounding neighbors, Asia-Pacific and Central Asia, for security and geostrategic concerns, it is nevertheless increasingly thinking and behaving in global terms [@nathan_chinas_2012]. Similarly, in terms of where China’s money goes and its economic influence concentrates, some countries are more important than others. However, no clear hierarchy or conclusive evidence has been drawn so far. The secrecy surrounding China's international development financing is puzzling. The painstaking work of researchers to document and analyze trends in China's development financing has illuminated a great deal about Beijing's approach to giving and lending. **They find** that China is far from the rogue donor that many have feared, but instead, China's ODA-like expenditures follow patterns similar to those of OECD-DAC donors **(citation needed)**. Hence, much like these traditional donors, China's foreign aid presents as a versatile foreign policy tool through which Beijing seeks to accomplish important objectives in international politics. These goals include international recognition that China is a great power and closer diplomatic ties with developing countries in what China calls ``South-South" cooperation.


However, the goals of facilitating cooperation and winning international recognition as a rising power are difficult to accomplish in secret. This, therefore, raises a natural question. *Do China’s foreign aid and debt allocation relate to public diplomacy and international recognition efforts? If so, how?*


We propose that despite the lack of formal reporting, Beijing can pursue international recognition and diplomacy with its overseas financing with the help of other complementary foreign policy activities. We look at the Chinese multidimensional public diplomacy efforts – foreign aid and debt operations, outward-facing news articles, and diplomatic visits. Past research has shown that two specific instruments may play special roles in complementing the foreign policy objectives of distributing money. First, media presence is one way that countries can generate attention and promote a positive spin on their activities to foreign audiences. As Nye [-@nye_public_2008-2] notes, daily communications that reach both domestic and foreign populations are a way to improve a country's soft power. Perhaps in recognition of this, Beijing has expanded its outward-facing state-sponsored media activities and news reporting over the past two decades. This has been done in part through the English version of *Xinhua*, China's top state-sponsored news agency.

Second, aside from expanding news media, China engages in more conventional forms of bilateral diplomacy via government-to-government diplomatic missions. Efforts to document Beijing's public diplomacy have revealed an expansive set of activities in which Beijing engages. These range from the financial to the cultural, and from elite-to-elite meetings to informational exchanges.

While public diplomacy and outward-facing state-sponsored media are not solely used to support China's overseas development financing, we believe they have clear overlapping purposes. In particular, diplomacy and coverage are critical *visible* activities that can complement the often opaque character of Beijing's development finance. Thus, to the extent that China's development finance is targeted at supporting image- and alliance-building activities, we hypothesize that recipients of China's overseas development assistance will also be disproportionate targets of media coverage in *Xinhua* to support China's image and to build publicity around its development activities, and be more frequent hosts of diplomatic missions from Beijing to support closer bilateral cooperation.


As we test these hypotheses, in our research design we take care to ensure that we delineate China's development financing according to types of assistance China offers. Until recently, many have mistakenly conflated Beijing's ODA-like giving with its other official financing (OOF). However, efforts to disentangle China's activities with respect to grants and low-interest loans (financing that would meet the OECD definition of official development assistance or ODA) from its activities with respect to higher interest loans and export credits (OOF) have unmasked a considerable divergence in goals. The conventional view is that while *aid* (ODA) is closely tied to Beijing's foreign policy goals, *debt* (OOF) is related to Beijing's commercial interests.^[See @dreher_banking_2022.] Thus, as we test our hypotheses, we also distinguish between Beijing-as-donor from Beijing-as-lender.


The results from the analysis of Dreher and his coauthors [-@dreher_banking_2022] provide a novel perspective on the ways that China applies additional instruments to complement the goals it pursues via its overseas development financing. While the findings overall are consistent with our hypotheses, they do so in ways that also problematize the neat distinction between China's use of aid and debt. In particular, we find that *Xinhua* coverage is disproportionately concentrated among China's ODA recipients, while no significant relationship exists between aid and diplomatic visits. Conversely, we find that debt is significantly linked to a greater frequency of bilateral diplomatic missions from Beijing, but no significant difference in *Xinhua* coverage. Together these findings reveal an intriguing pattern: Beijing likes to talk about its aid recipients but prioritizes diplomacy with its debtors.


Aid recipient countries disproportionately get more media attention from *Xinhua* to report their economy and needs for development projects and aid. Notably, *Xinhua* does not just promote China’s efforts to offer aid to those countries in need but also gives a rounded picture of those countries’ economic conditions that justify their bases of needs. 


Another implication of our finding is that Beijing is more likely to lend money to its “friends”: countries with more cordial diplomatic relations tend to have closer political interests and ties. A 2018 Belt and Road Initiative foreign policy assessment report from Washington [@hurley_examining_2019] highlights that lending indicates Beijing’s economic interests and strategic dominance – China tends to lend its loans to vulnerable states with debt distress in exchange for unfair deals and strategic concessions. Brautigam [-@brautigam_critical_2020] calls the Chinese ``debt-trap diplomacy" a meme based on collective fear of the Chinese threat rather than sound empirical evidence. Our finding suggests that China is more likely to provide loans to diplomatically aligned countries. For instance, Russia, one of China’s closest allies, receives the highest amount of lending on average among 142 countries but no aid at all between 2002 and 2017. In contrast, Iraq shows the opposite pattern: it receives the highest amount of aid from China during the period of our investigation, but it does not receive any loans. 


# Xinhua’s Global Horizons

*Xinhua* is firmly under the control of the CCP’s Central Propaganda Department. In 2013, President Xi Jinping exhorted the Propaganda Department to “tell Chinese stories well,” and *Xinhua* news agency is at the forefront [@xinhua_xi_2013].  It also has an increasingly global reach to produce millions of articles in the past decade with hundreds of bureaus worldwide. Yet, *Xinhua*’s news reports should not be dismissed as mere propaganda or empty slogans. *Xinhua* presents itself as a balanced and fact-based news agency, not a government mouthpiece [@brazys_chinas_2020]. This outward-facing Chinese official media, whose mission as a key disseminator of the Party’s narrative to foreign audiences, may inform us of the PRC government’s initiatives of presenting Chinese perspectives of real-time events to global audiences. 

*Xinhua* is global, but also serves as the main domestic media outlet. International and domestic audiences are two separate audiences, as *Xinhua* will produce its news contents in English, French, Spanish, Korean and Japanese, as well as Chinese. Brazys and Dukalaskis [-@brazys_chinas_2020] analyze how different countries are talked about in *Xinhua*’s articles in Chinese and in languages other than Chinese. They find that domestic-facing articles about other countries or regions are neither negative nor neutral, while articles about China are slightly positive. In contrast, *Xinhua*’s outward-facing articles use overall positive tones to report other countries and regions, including the United States. When characterizing China to foreign audiences, the tone is much more positive than the tone it uses for Chinese readers, or stories about any other country to both audiences.

The Chinese government is acutely sensitive to China’s image in foreign media coverage. In addition to building *Xinhua* as a global news agency, China also invests in ownership stake in media companies in other developing countries. A working paper by Sundquist [-@sundquist_telling_2022] shows that the media outlets after the ownership change adopt a more friendly tone when reporting China. This finding is consistent with the conventional argument that media ownership exerts a homogenizing effect on the newspapers’ coverage of foreign policy [@baum_media_2019]. Sending constructive media messages and shaping stories about China to international audiences is critical to Beijing, and *Xinhua* is not alone in this initiative. 

\clearpage

# References